// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class InvalidLoginTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void invalidLogin() {
    driver.Navigate().GoToUrl("https://accounts.google.com/ServiceLogin/signinchooser?passive=1209600&continue=https%3A%2F%2Faccounts.google.com%2F&followup=https%3A%2F%2Faccounts.google.com%2F&flowName=GlifWebSignIn&flowEntry=ServiceLogin");
    driver.Manage().Window.Size = new System.Drawing.Size(1550, 838);
    driver.FindElement(By.CssSelector(".JDAKTe:nth-child(3) .BHzsHc")).Click();
    driver.FindElement(By.Id("identifierId")).SendKeys("TestSelenium1607");
    driver.FindElement(By.CssSelector(".ZFr60d")).Click();
    driver.FindElement(By.Name("password")).SendKeys("adffefefegg");
    driver.FindElement(By.CssSelector("#passwordNext > .CwaK9")).Click();
  }
}
